### ISSUE TITLE
Error 404 with multibranch pipeline with parameters

### ISSUE THREAD

**Issue by fernando1989mg** [enflo/jenkins-action#1]
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /job-hooly-ms-py2-auth/swagger/buildWithParameters. Reason:
<pre>    Not Found</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a><hr/>

</body>
</html>

**Comment by enflo** [comment]
Hello, 
In your path you have leftover /buildWithParameters, because it is set by default in the script, you should try with only /job-hooly-ms-py2-auth/swagger

Thank you very much for detecting this error, I will prepare a new version to contemplate this option

**Comment by enflo** [comment]
Can @fernando1989mg try the new release?
